#ifndef PS_RENDERFLAGS_H
#define PS_RENDERFLAGS_H

enum RenderFlags {
    DRAWING_OPTION = 0x1,     // 1
    CULLING_OPTION = 0x2,     // 2
    CULLING_VISIBLE = 0x4,    // 3
    ALPHA_ENABLE = 0x8,       // 4
    ALPHA_STATE = 0x30,       // 5-6
    TEXTURE_MAPPING = 0x40,   // 7
    COLOR_ENABLE = 0x80,      // 8
    Z_ENABLE = 0x100,         // 9
    Z_TYPE = 0x600,           // 10-11
    LIGHTING_ENABLE = 0x800,  // 12
    BACKFACE_CULLING = 0x1000, // 13
    CLIPPING = 0x2000,         // 14
    ENVIRONMENTMAP = 0x4000,   // 15
    SPECULAR = 0x8000,         // 16
    ANIMATION_TEXUTRE = 0x10000,  // 17
    MORPH_TARGET = 0x20000,       // 18
    SKELETAL_ANIMATION = 0x40000, // 19
    ALPHA_MAPPING = 0x80000      // 20
};

#define ZSTATE(x) ((1 << 8) | (x << 9))

#define RENDERENVIRONMENTAL (DRAWING_OPTION | ENVIRONMENTMAP | LIGHTING_ENABLE | ZSTATE(3) | TEXTURE_MAPPING)

#define RENDERTEXTUREMAPPED (DRAWING_OPTION | TEXTURE_MAPPING | ZSTATE(3))

#define RENDERCOLORED (DRAWING_OPTION | COLOR_ENABLE | ZSTATE(3))

#define RENDERLIT (LIGHTING_ENABLE | COLOR_ENABLE)

#define RENDERNORMAL (DRAWING_OPTION | ZSTATE(3) )

#endif