#ifndef PS_PIPELINEINTERNAL_H
#define PS_PIPELINEINTERNAL_H

#define DEFAULT_GS_REG_PCB 0x40

#define DEFAULT_VU1_HEADER_PCB 0x41

#define DEFAULT_OBJ_WVP_PCB 0x42

#define LIGHT_BUFFER_PCB 0x43

#define DEFAULT_STAGE2_MATRIX_PCB 0x44

#define ALPHAMAP_SETUP_GS_PCB 0x56

#define ALPHAMAP_RENDERPASS_TWO_PCB 0x57

#define ALPHAMAP_RENDERPASS_THREE_PCB 0x58

#define ALPHAMAP_RENDERPASS_FINAL_PCB 0x59

#define ALPHAMAP_VU1_HEADER_PCB 0x60

#define MORPHTARGET_INTERPOLATOR_PCB 0x61

#define MORPHTARGET_VU1_HEADER_PCB 0x62

#define SKINNED_VU1_HEADER_PCB 0x63

#define SKINNED_DMA_UPLOAD_PCB 0x64

#define SETUP_BLENDING_PCB 0x65

#define SETUP_MAP_TEXTURE_PCB 0x66

#endif